version: '3.8'

services:
  backend:
    restart: always
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:3000
    volumes:
      - ./backend/src:/app/src
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VITE_PUBLIC_API_URL: ${VITE_PUBLIC_API_URL}
    restart: always
    volumes:
      - ./frontend/src:/app/src
    ports:
      - ${FRONTEND_PORT}:8000
    depends_on:
      - backend

volumes:
  backend:
    driver: local